name: Rust Build

on:
  push:
    branches:
      - main # or the branch you want to trigger this workflow
  pull_request:
    branches:
      - main # or the branch you want to trigger this workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # or the version you need

    - name: Install dependencies and build webui
      run: |
        cd webui
        npm install
        npm run build

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build Rust project for x86_64
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Build Rust project for aarch64
      run: cargo build --release --target aarch64-unknown-linux-gnu
      
    - name: Build Rust project for Windows
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Archive production artifacts for Windows
      uses: actions/upload-artifact@v3
      with:
        name: Windows x86_64
        path: target/x86_64-pc-windows-msvc/release/ew

    - name: Archive production artifacts for x86_64
      uses: actions/upload-artifact@v3
      with:
        name: Linux x86_64
        path: target/x86_64-unknown-linux-gnu/release/ew
    
    - name: Archive production artifacts for aarch64
      uses: actions/upload-artifact@v3
      with:
        name: Linux aarch64
        path: target/aarch64-unknown-linux-gnu/release/ew

